name: Generate Snake

on:
  schedule:
    # Roda automaticamente a cada 24 horas (à meia-noite)
    - cron: "0 0 * * *"
  
  # Permite rodar a automação manualmente quando você quiser
  workflow_dispatch:

  # Roda a cada push na branch main/master
  push:
    branches:
    - main
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 1. Gera o jogo da cobrinha a partir do perfil com as cores personalizadas em azul
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#0A66C2&color_dots=#ebedf0,#b6d4fe,#6ea8fe,#3d8bfd,#0d6efd
            dist/github-contribution-grid-snake-dark.svg?color_snake=#3498db&color_dots=#161b22,#0d2d54,#0052a3,#0070e0,#3498db
          
      # 2. Envia os arquivos gerados para a branch "output"
      - name: push github-contribution-grid-snake.svg to the github-pages branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
